title: Yuma Kanogi - Portfolio
description: I mainly focus on projects in science and engineering fields.
lang: ja
url: "https://entfrem0.github.io"
baseurl: "/Portfolio"
permalink: pretty
markdown: kramdown
highlighter: rouge
google_fonts: "https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700&display=swap"

collections: {}

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      sidebar_title: Same Categories

navigation:
  - title: Portfolio
    url: /

sections:
  test:
    title: Test1
    description: Test1
    url: /test/
  test2:
    title: Test2
    description: Test2
    url: /test2/

# 新しく記事を作る際は、sectionsに項目を作る。titleとdescriptionとurlも加える

kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: 2..3

sass:
  style: compressed
